<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <NpmDependencies>
      <NpmPackage Name="cytoscape" Version="gt= 3.31.5 lt 3.32.5" ResolutionStrategy="Max" />
    </NpmDependencies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Main.fs" />
    <None Include="wsconfig.json" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>